### ISSUE TITLE
Several properties are missing doc strings

### ISSUE THREAD

**Issue by kennyjwilli** [pulumi/pulumi-datadog#8] opened 2019-06-27 15:46 UTC
Several properties in this provider are missing docs. It's not clear what the pattern is for the missing docs. For example, a "top-level" [property `readOnly`](https://github.com/pulumi/pulumi-datadog/blob/101d42e6cc66710053b55a7b8a178b1ef3458a8f/sdk/nodejs/screenBoard.ts#L141) is missing a doc string but has one on the [Terraform site](https://www.terraform.io/docs/providers/datadog/r/screenboard.html#read_only). 

It appears that all nested properties are missing docs. For example, [`recurrence`](https://github.com/pulumi/pulumi-datadog/blob/101d42e6cc66710053b55a7b8a178b1ef3458a8f/sdk/nodejs/downtime.ts#L239) in Downtime. 

Another, possibly related issue, is all nested properties are generated on a single line. The previously linked `recurrence` and [`widgets`](https://github.com/pulumi/pulumi-datadog/blob/101d42e6cc66710053b55a7b8a178b1ef3458a8f/sdk/nodejs/screenBoard.ts#L157) are examples.

**Comment by stack72** [comment] 2019-09-11 17:13
@kennyjwilli is this still the case? We have invested a LOT on our docs recently

**Comment by mikhailshilkov** [comment] 2023-08-01 14:39
I spot-checked the links above and the docs are either fixed, or the property does not exist yet. Since the issue is so old, I'll go ahead and close it as fixed.

**Closed by mikhailshilkov** 2023-08-01 14:39 UTC
Labels: kind/bug, resolution/fixed, area/docs
