### ISSUE TITLE
Error occurred when orchestrating Synthetics Test for SSL

### ISSUE THREAD

**Issue by shadeven** [pulumi/pulumi-datadog#129] opened 2021-05-06 02:30 UTC
We are having issue orchestrating Synthetics test for SSL subtype. The pulumi code is written in TypeScript and the error as below:
```
error: 1 error occurred:
        * updating urn:pulumi:prod::datadog-infrastructure::datadog:index/syntheticsTest:SyntheticsTest::datadog-infrastructure-synthetics-test-tmr-ssl: error updating synthetics test: 400 Bad Request: {"errors": ["properties.config.properties.request.additionalProperties: Additional properties are not allowed (u'timeout' was unexpected)\n\nFailed validating 'additionalProperties' in schema['properties']['config']['properties']['request']:\n    {'additionalProperties': False,\n     'properties': {'certificate': {'additionalProperties': False,\n                                    'properties': {'cert': {'additionalProperties': False,\n                                                            'properties': {'content': {'maxLength': 51200,\n                                                                                       'type': 'string'},\n                                                                           'filename': {'maxLength': 1500,\n                                                                                        'type': 'string'},\n                                                                           'updatedAt': {'maxLength': 1500,\n                                                                                         'type': 'string'}},\n                                                            'required': ['filename'],\n                                                            'type': 'object'},\n                                                   'key': {'additionalProperties': False,\n                                                           'properties': {'content': {'maxLength': 51200,\n                                                                                      'type': 'string'},\n                                                                          'filename': {'maxLength': 1500,\n                                                                                       'type': 'string'},\n                                                                          'updatedAt': {'maxLength': 1500,\n                                                                                        'type': 'string'}},\n                                                           'required': ['filename'],\n                                                           'type': 'object'}},\n                                    'required': ['cert', 'key'],\n                                    'type': 'object'},\n                    'host': {'maxLength': 6000, 'type': 'string'},\n                    'port': {'anyOf': [{'maximum': 65535,\n                                        'minimum': 1,\n                                        'type': 'integer'},\n                                       {'maxLength': 51200,\n                                        'pattern': '\\\\{\\\\{ *([A-Z][A-Z0-9_]+[A-Z0-9]) *\\\\}\\\\}',\n                                        'type': 'string'}]}},\n     'required': ['host', 'port'],\n     'type': 'object'}\n\nOn instance['config']['request']:\n    {u'host': u'example.org', u'port': 443, u'timeout': 60}"]}
```
We attempted a different approach by manually provisioning the Synthecits Test, and then importing the resource using `pulumi import`. Interestingly we noticed the `request` property in the generated code is an array instead of an object, and obviously it does not even compile. If we change it to a `request` object, then it gives the same error as above.

```
new datadog.SyntheticsTest(
  'datadog-infrastructure-synthetics-test-tmr-ssl',
  {
    assertions: [
      {
        operator: 'isInMoreThan',
        target: '30',
        type: 'certificate',
      },
    ],
    locations: ['aws:ap-southeast-2'],
    message: '',
    name: 'tmr-ssl',
    optionsList: {
      acceptSelfSigned: true,
      minLocationFailed: 1,
      tickEvery: 900,
    },
    request: [
      {
        host: 'example.org',
        port: 443,
        timeout: 60,
      },
    ],
    status: 'live',
    subtype: 'ssl',
    type: 'api',
  },
  {
    protect: true,
  }
);
```

## Expected behavior

It is expected to orchestrate the Synthetics Test successfully.
## Current behavior

The above error was thrown.
## Steps to reproduce

1. Run `pulumi up` on the pulumi code as above.

## Context (Environment)

Package versions:
1. `@pulumi/datadog: 3.0.0`
2. `@pulumi/pulumi: 3.2.0`

OS version:
Fedora 34

**Comment by mikhailshilkov** [comment] 2021-05-06 10:43
I believe it's a dupe of https://github.com/pulumi/pulumi-datadog/issues/102

**Closed by mikhailshilkov** 2021-05-06 10:43 UTC
Labels: kind/bug, resolution/duplicate
